### ISSUE TITLE
Active Storage - Analyze Job - Always fails because of after_create_commit callback

### ISSUE THREAD

**Issue by Laykou** [palkan/isolator#23]
When used together with Rails 6 and ActiveStorage, this fails always, as ActiveStorage automatically always tries to schedule the AnalyzeJob after the record is created:

```
Isolator::BackgroundJobError:
        You are trying to enqueue background job inside db transaction. In case of transaction failure, this may lead to data inconsistency and unexpected bugs
        Details: ActiveStorage::AnalyzeJob (#<ActiveStorage::Blob:0x00005588a27565e0>)
      # /builds/smartq/qflow/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.0/lib/active_job/enqueuing.rb:22:in `perform_later'
      # /builds/smartq/qflow/vendor/bundle/ruby/2.6.0/gems/activestorage-6.0.0/app/models/active_storage/blob/analyzable.rb:37:in `analyze_later'
      # /builds/smartq/qflow/vendor/bundle/ruby/2.6.0/gems/activestorage-6.0.0/app/models/active_storage/attachment.rb:37:in `analyze_blob_later'
      # /builds/smartq/qflow/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `block in make_lambda'
      # /builds/smartq/qflow/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:264:in `block in conditional'
```

Which is called from Blob: `after_create_commit :analyze_blob_later, :identify_blob`

**Comment by palkan** [comment]
Does this happen in all environments or, for example, only in test or development?

**Comment by palkan** [comment]
Closed as stale

**Comment by ocha** [comment]
I was able to reproduce same error. If anyone else is having this issue, it is caused because this gem was required **before** `database_cleaner` gem. One I fixed it (there is a note for this in README), error went away
