### ISSUE TITLE
Error raised when query has invalid encoding

### ISSUE THREAD

**Issue by tiagotex** [palkan/isolator#43]
We recently tried to add isolator to our app and it made some tests.

We have tests that confirm that sending invalid UTF-8 chars works (they are sanitized), but now that query is triggering a crash in isolator code.

This is the app code that triggers the failure:

```ruby
User.find_or_initialize_by(email: "Invalid \xAD char")
```

We get the error `ArgumentError: invalid byte sequence in UTF-8`, this is the stack trace after that call is made:

```
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/isolator-0.8.0/lib/isolator/orm_adapters/active_support_subscriber.rb:13:in `match?'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/isolator-0.8.0/lib/isolator/orm_adapters/active_support_subscriber.rb:13:in `block in subscribe!'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/fanout.rb:189:in `finish'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/fanout.rb:62:in `block in finish'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/fanout.rb:62:in `each'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/fanout.rb:62:in `finish'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/instrumenter.rb:30:in `instrument'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `log'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:199:in `execute'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/mysql/database_statements.rb:41:in `execute'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/marginalia-1.11.1/lib/marginalia.rb:71:in `execute_with_marginalia'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:210:in `execute_and_free'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/mysql/database_statements.rb:46:in `exec_query'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:489:in `select'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:107:in `select_all'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/querying.rb:46:in `find_by_sql'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:824:in `block in exec_queries'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:842:in `skip_query_cache_if_necessary'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:811:in `exec_queries'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:626:in `load'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:250:in `records'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation/finder_methods.rb:499:in `find_take'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation/finder_methods.rb:98:in `take'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation/finder_methods.rb:81:in `find_by'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/relation.rb:227:in `find_or_initialize_by'",
"/dev/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.4/lib/active_record/querying.rb:21:in `find_or_initialize_by'"
```

The error comes from calling `match?` with a value that might not be in the right encoding.

```ruby
module Isolator
  # ActiveSupport notifications listener
  # Used for ActiveRecord and ROM::SQL (when instrumentation is available)
  module ActiveSupportSubscriber
    START_PATTERN = %r{(\ABEGIN|\ASAVEPOINT)}xi
    FINISH_PATTERN = %r{(\ACOMMIT|\AROLLBACK|\ARELEASE|\AEND TRANSACTION)}xi

    def self.subscribe!(event)
      ::ActiveSupport::Notifications.subscribe(event) do |_name, _start, _finish, _id, query|
        connection_id = query[:connection_id] || query[:connection]&.object_id || 0
        Isolator.incr_transactions!(connection_id) if START_PATTERN.match?(query[:sql])
        Isolator.decr_transactions!(connection_id) if FINISH_PATTERN.match?(query[:sql])
      end
    end
  end
end
```

As ActiveRecord doesn't raise an error, I would expect Isolator to also handle strings that have the wrong encoding (maybe force UTF-8), what do you think?

I'm available to submit a PR for the fix. Thank you for the nice gem 💚

**Comment by palkan** [comment]
Thanks for reporting!
That's an interesting case.

> I'm available to submit a PR for the fix.

That would be awesome!

I think, subscribing to an event shouldn't break the actual code execution (that's probably an ActiveSupport::Notifications concern 🤔).
As far as I can see, the only code that could raise and out of our control is `Regexp#match?`.

So, I suggest adding a safer version, say, `Regexp#safe_match?` which catches ArgumentError and return nil. And we can use a Refinement for that! WDYT?

**Comment by yogeshjain999** [comment]
Good idea about `safe_match?`.

Though, instead of catching `ArgumentError` and returning `nil` (which would ignore that occurrence I suppose), maybe we can replace invalid occurrences with blank string as suggested [here](https://thoughtbot.com/blog/fight-back-utf-8-invalid-byte-sequences) 🤔

**Comment by palkan** [comment]
Yeah, I like it. I guess, here is the code snippet we can use: https://github.com/thoughtbot/griddler/blob/2ae3a99b8c59d8c68adffd6e109b1b83fd32f26e/lib/griddler/email.rb#L153-L159
